Se ha añadido una descripción inicial del problema
carlotiii30/organizacionSemanal pull request #1
Opened 2023-09-15 09:04 UTC by carlotiii30

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, porque el problema es planteado por un estudiante, y, además, es bastante genérico, es decir, en realidad, cualquier estudiante de universidad podría tenerlo.
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Sí, porque se busca una organización dinámica que se adapte a las necesidades del estudiante.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Sí, porque se necesita una sincronización de horarios para que no sean solapados y un algoritmo que marque qué actividad es más conveniente realizar.
* [x] ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
Se requieren tanto datos almacenados en la nube, como los horarios de la facultad, u horarios del gimnasio; como especificaciones concretas del usuario para personalizar la experiencia.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-15 09:57 UTC, carlotiii30 commented
* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-15 15:33 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
> 
>     * [x]  ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el
>       `README`?
> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
> 
>     * [ ]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

Esto debes ponerlo en el cuerpo del PR, no en el comentario.

2023-09-15 15:35 UTC, JJ requested changes
El objetivo es que describas un problema, no qué vas a hacer. Lo que se vaya a hacer se irá decidiendo en las fases siguientes de desarrollo.

2023-09-15 15:35 UTC, JJ commented on README.md
> +El objetivo es crear una aplicación que ayude a un usuario, estudiante, a organizar su agenda semanal. Las actividades consideradas son: asistir a clase en la universidad, ir a ciertas clases del gim
Tienes que describir un problema, no una solución.

2023-09-16 11:24 UTC, JJ approved these changes
:+1:  Pero el problema es demasiado difuso y tendrás que concretarlo en el objetivo 1. Por otro lado, en la configuración puesta no has mostrado que esté configurado el correo correctamente ni que hayas configurado correctamente el par de claves ssh; el primero parece que sí está configurado y del segundo imagino que también, porque el URL es de ssh, pero lo pedía explícitamente en el guión.

2023-09-22 07:23 UTC, merged