[IV-23-24] Objetivo 3
carlotiii30/organizacionSemanal pull request #16
Opened 2023-11-11 13:02 UTC by carlotiii30

2023-11-15 11:06 UTC, PabloBarTo requested changes
Buenass! Te dejo aquí unos cambios que yo creo que pueden ser de ayuda.

2023-11-15 14:57 UTC, carlotiii30 commented
> Buenass! Te dejo aquí unos cambios que yo creo que pueden ser de ayuda.

Muchas gracias, ya he actualizado con los cambios sugeridos.

2023-11-15 14:58 UTC, carlotiii30 commented on docs/gestor_tareas.md
> +# Gestor de tareas
Añadidos en linea 17.

2023-11-15 17:31 UTC, PabloBarTo requested changes
Te he dejado otros cambios que yo creo que pueden ayudar a que el profesor te lo apruebe. Quitando eso lo demás si lo veo bien.

2023-11-15 17:31 UTC, PabloBarTo commented on docs/gestor_tareas.md
> +## Criterios de elección
Ahora sí veo bien la estructura, pero trataría de poner unos criterios que se puedan medir como tal ya que por ejemplo  la facilidad no es algo que tu puedas medir. Lo puedes intuir a simple vista pero no puedes medirlo en sí.

2023-11-16 08:23 UTC, carlotiii30 commented on docs/gestor_tareas.md
> +## Criterios de elección
Corregido, muchas gracias.

2023-11-17 08:17 UTC, carlotiii30 commented
@JJ Listo para revisión

2023-11-17 08:50 UTC, JJ requested changes
Trata de ver qué opciones más hay y los otros comentarios, por favor.

2023-11-17 08:50 UTC, JJ commented on README.md
> +Una persona necesita una solución para organizar, de manera eficiente, su semana, ya
Por favor, tratad de hacer estas correcciones entre PRs, porque aquí añaden ruido a la corrección que hay que hacer del objetivo.

2023-11-17 08:50 UTC, JJ commented on docs/gestor_dependencias.md
> +
¿no faltaría una aquí?

2023-11-17 08:50 UTC, JJ commented on docs/gestor_dependencias.md
> +* Simpleza: Claridad en el proceso de añadir, eliminar y actualizar paquetes.
Simplicidad y simpleza creo que no son lo mismo.

2023-11-17 08:50 UTC, JJ commented on docs/gestor_dependencias.md
> +### Historia
Agh, no, historia no, ¿por qué?

2023-11-17 08:50 UTC, JJ commented on docs/gestor_tareas.md
> +* [Gulp](#gulp): https://gulpjs.com
Gulp está irremediablemente obsoleto; comprueba en Snyk Advisor su puntuación.

2023-11-17 08:50 UTC, JJ commented on docs/gestor_tareas.md
> +## Criterios de elección
Resuelve, por favor

2023-11-17 09:21 UTC, carlotiii30 commented on docs/gestor_tareas.md
> +* [Gulp](#gulp): https://gulpjs.com
En la descripción de Gulp se menciona.

2023-11-17 09:22 UTC, carlotiii30 commented on docs/gestor_dependencias.md
> +
Añadida en línea 12.

2023-11-17 09:23 UTC, JJ approved these changes
👍

2023-11-17 09:37 UTC, merged