[IV-23-24]Objetivo 4
carlotiii30/organizacionSemanal pull request #26
Opened 2023-11-18 10:15 UTC by carlotiii30

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-21 17:04 UTC, carlotiii30 commented
@JJ Han pasado 3 días y ninguno de los revisores me ha dicho nada, ¿puede corregírmelo usted?

2023-11-22 07:45 UTC, JJ requested changes
Por favor, aclara un poco los términos y conceptos de este objetivo. DDD era lo que había que aplicar en el objetivo 2.

2023-11-22 07:45 UTC, JJ commented on docs/herramientas_test.md
> +## DDD
Domain driven design no tiene nada que ver con los tests; quizás quieras decir BDD.

2023-11-22 10:29 UTC, carlotiii30 commented on docs/herramientas_test.md
> +## DDD
Cambiado.

2023-11-22 19:17 UTC, JJ requested changes
Has hecho una entrega muy completa; desgraciadamente, creo que entre tanto texto se pierde realmente lo que es necesario para entender las decisiones que has tomado. Entre otras cosas, debes decir claramente antes de cada uno de los tipos de herramientas que vas a elegir cuales son los criterios que te harán decantarte por uno u otro, y luego a continuación en cada herramienta ceñirte a esos criterios. Si no la cantidad de literatura que se puede escribir sobre cada una no tiene límite ni término.

Te recuerdo también la necesidad de **no** usar git add . y de que `node_modules` no esté de ninguna forma entre el código del repositorio.

2023-11-23 08:07 UTC, carlotiii30 commented
@JJ Listo para revisión.

2023-11-23 09:04 UTC, JJ requested changes
Tendrías que intentar realmente testear la lógica de negocio; no sólo añadir actividades y ver que están añadidas. Aparte, hay algunos otros cambios menores que convendría que tuvieras en cuenta.

2023-11-23 09:04 UTC, JJ commented on docs/herramientas_test.md
> +* Chai: https://www.chaijs.com
¿Esto es chai o assert?

2023-11-23 09:04 UTC, JJ commented on docs/herramientas_test.md
> +- Node.js
Node es un runtime, no un framework integrado (aunque tiene test y aserciones en las últimas versiones)

2023-11-23 09:04 UTC, JJ commented on docs/herramientas_test.md
> +[Yarn](gestor_dependencias.md) proporciona una interfaz de línea de comandos
Igual que antes, ¿por qué no pones las otras opciones?

2023-11-23 15:31 UTC, carlotiii30 commented
> Tendrías que intentar realmente testear la lógica de negocio; no sólo añadir actividades y ver que están añadidas. Aparte, hay algunos otros cambios menores que convendría que tuvieras en cuenta.

He implementado una función para extraer los datos de un horario, ya que vamos a trabajar con esos datos, además de la posibilidad de añadir eventos. ¿Es suficiente?

2023-11-24 06:29 UTC, JJ commented
> > Tendrías que intentar realmente testear la lógica de negocio; no sólo añadir actividades y ver que están añadidas. Aparte, hay algunos otros cambios menores que convendría que tuvieras en cuenta.
> 
> He implementado una función para extraer los datos de un horario, ya que vamos a trabajar con esos datos, además de la posibilidad de añadir eventos. ¿Es suficiente?

¿Crees que tu cliente en #2 se quedaría satisfecha?

> Quiero una forma de optimizar mi tiempo para poder equilibrar mis estudios, el ejercicio físico y las citas médicas sin sentirme abrumada.

Recuerda, las metodologías en ingeniería lo que buscan es que la propia ingeniera sea capaz, autónomamente, de discernir si está haciendo lo correcto para la clienta o no.

2023-11-25 11:12 UTC, carlotiii30 commented
@JJ Listo para revisión.

2023-11-26 10:52 UTC, JJ requested changes
Creo que ya hay una lógica de negocio, así que hemos avanzado; el problema es que hay que poner en práctica una serie de metodologías para que el código sea más sencillo de entender para ti en el futuro, y también para mi que lo estoy revisando; también los tests deben tener un formato que se acerque a la HU, no simplemente comprobar que las salidas son las que se andan buscando.

2023-11-26 10:52 UTC, JJ commented on src/optimizador_semanal.ts
> +    public getHorario(): string[][] {
Asegúrate que sólo tienes los getters que sean realmente necesarios.
Además, los getters en TypeScript (y JS) se pueden declarar con `get`

2023-11-26 10:52 UTC, JJ commented on src/optimizador_semanal.ts
> +        Array.from({ length: 29 }).forEach((_, index) => {
¿29?

2023-11-26 10:52 UTC, JJ commented on src/optimizador_semanal.ts
> +            if (actividad.getDuracion() === undefined)
Ninguna operación en un objeto debe dejarlo en un estado indefinido. `actividad` debería de estar definida de tal forma que *siempre* su estado sea correcto. Por eso se hace tanto énfasis en objetos-valor inmutables. Entre otras cosas, sabes que son correctos.

2023-11-26 10:52 UTC, JJ commented on src/actividad.ts
> +    public calcularDuracion(): number | undefined{
Mirando como se usa, vuelvo a insistir en el hecho de que uses objetos inmutables, con una buena aplicación de DDD. La duración de una actividad no puede confiar en dos funciones diferentes: debería llamarse a una sola, que debería *siempre* devolver un valor correcto.

2023-11-26 10:52 UTC, JJ commented on src/optimizador_semanal.ts
> +            if (diaIndex !== -1 && horaIndex !== -1 && duracion) {
Usar flags con valores inválidos para "no encontrdo" es un antipatrón bastante común, que sé que os han inculcado, pero es siempre una mala idea. Una variable debe siempre contener un valor válido o `undefined` o `null`. Valores que necesiten interpretación no es algo que sea sostenible en el desarrollo a largo plazo.

2023-11-26 10:52 UTC, JJ commented on src/optimizador_semanal.ts
> +                while (duracion > 0 && celdasDisponibles.length > 0) {
Recuerda que hablé en clase de la complejidad ciclomática. Aquí tienes, más arriba, bucles con 5 niveles de profundidad; este también está dentro de un if y tiene varios niveles.
El SRP (single responsibility principle) lo que dice es que una función tiene que hacer una cosa y solo una. Y para trabajar en tests lo que anima es a crear funciones lo más atómics posibles. Código limpio también dice que una función debe tener, como máximo, un pantallazo.

Por favor, trata de simplificar un poco, extrayendo bucles, precalculando cosas, y demás. Un programa debe de parecerse lo más posible a la descripción del algoritmo que sigue. Entre otras cosas, un bucle con 5 niveles de profundidad es imposible de testear, porque el número de combinaciones posibles (principio y fin de bucles, ramas del if) explota.

Convendría que mirararas la función `map` y la `filter` de JS. La primera convierte arrays y hashes, la segunda extrae elementos del array que cumplan algo. Todos o la mayoría de las funciones que estás haciendo aquí se solucionan con una combinación de maps y filtros.

2023-11-26 10:52 UTC, JJ commented on test/optimizador_semanal.test.ts
> +        actividad.setDuracion(2);
¿Esta duración no se conocía cuando se creó la actividad?

2023-11-26 10:52 UTC, JJ commented on test/optimizador_semanal.test.ts
> +        expect(optimizador.getHorario()[7][1]).toBe("Estudiar para el examen");
En general, no tienes que probar que la salida sea la esperada. Tienes que comprobar que se trate de lo que busca la cliente. Diferentes algoritmos pueden dar diferentes salidas.

2023-11-26 10:52 UTC, JJ commented on test/optimizador_semanal.test.ts
> +        expect(optimizador.getHorario()[4][4]).toBe("Facultad");
Aparte de lo dicho arriba, por favor aplica DRY.

2023-11-27 18:11 UTC, carlotiii30 commented on src/optimizador_semanal.ts
> +        Array.from({ length: 29 }).forEach((_, index) => {
Cada fila de la matriz horario es una hora, en punto o y media, comprendida entre las 7:00 y las 21:00.
21 - 7 = 14 
14 x 2 (cada media hora) = 28
28 + 1 (días de la semana) = 29

2023-11-27 18:13 UTC, carlotiii30 commented
> Creo que ya hay una lógica de negocio, así que hemos avanzado; el problema es que hay que poner en práctica una serie de metodologías para que el código sea más sencillo de entender para ti en el futuro, y también para mi que lo estoy revisando; también los tests deben tener un formato que se acerque a la HU, no simplemente comprobar que las salidas son las que se andan buscando.

Creo que ya están todos los cambios sugeridos resueltos.

2023-11-28 07:34 UTC, JJ commented on src/optimizador_semanal.ts
> +        Array.from({ length: 29 }).forEach((_, index) => {
Por eso es una buena práctica usar constantes con un nombre significativo en vez de literales. Conviene que esas mismas cuentas las reproduzcas en constantes, para que tanto la persona que revisa como tú misma dentro de 6 meses sepas cómo se crea ese número.

Pero espera, ¿por qué sumas fragmentos de media hora a un día de la semana? Mira por favor los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-4.md#sobre-la-programaci%C3%B3n):

> Poner elementos con tipo diferente en un array, y sólo usar los elementos que sigan algún criterio. En lenguajes modernos con tipos de datos avanzados, debe usarse el tipo más adecuado para cada tipo de dato.

2023-11-28 07:51 UTC, JJ requested changes
Creo que ha mejorado bastante, y has incorporado bastantes buenas prácticas al código; creo que nos acercamos más a superar el objetivo, pero todavía habría que hacer un pequeño esfuerzo adicional para satisfacer a tu clienta, estudiante del doble grado de Ciencias de Actividad Física y del Deporte y Nutrición Humana y Dietética.

2023-11-28 07:51 UTC, JJ commented on docs/herramientas_test.md
> +### Características
¿Sigues creyendo que este material es necesario para entender tu decisión?

2023-11-28 07:51 UTC, JJ commented on src/actividad.ts
> +    private Tarea: {
¿Estás definiendo una clase privada dentro de una clase? ¿Qué funcionalidad se consigue con esto?

2023-11-28 07:51 UTC, JJ commented on src/actividad.ts
> +        Descripcion: string,
¿Está segura que poner las variables de instancia o claves de un objeto en mayúsculas sigue las mejores prácticas?

2023-11-28 07:51 UTC, JJ commented on src/actividad.ts
> +        if (duracion === undefined) {
1. En la línea 26 estás asignand a `Duracion` un valor antes de saber si está definida o no.
2. ¿Qué ocurre si la duración no es consistente con el contenido de `hora`?
3. ¿Estás segura que necesitas `hora` y `duracion`? (Tanto en el argumento como en la clase (que es posible que tampoco necesites)

2023-11-28 07:51 UTC, JJ commented on src/optimizador_semanal.ts
> +        if (actividad.descripcion != null)
1. ¿Hay alguna posibilidad, en el diseño de la clase actividad, que esta descripción sea nula?
2. Si es nula, ¿no  habrá que tirar alguna excepción? Que un método no haga nada (y no diga nada al respecto) no parece un comportamiento aceptable.

2023-11-28 07:51 UTC, JJ commented on src/optimizador_semanal.ts
> +        const fijas = this.actividades.filter(actividad => actividad.tipo == TipoActividad.FIJA);
Si el patrón habitual de código es llamarlas con un filtro, ¿no debería incluirse ese filtro en la propia función?
Por otro lado, buen uso de `filter`

2023-11-28 07:51 UTC, JJ commented on test/optimizador_semanal.test.ts
> +            ["", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES"],
Ah, ya veo por qué tiene 29 elementos. Digo lo mismo que antes, deberías usar tipos de datos específicos: o franja horaria, o diaria. En el objetivo 2 tenéis que hacer una modelización del problema y se trata precisamente de eso. Que tengas que imprimirlo así no implica que tengas que hacer un modelo incorrecto del problema.

2023-11-28 07:51 UTC, JJ commented on test/optimizador_semanal.test.ts
> +        const expectedHorario = [
Como os comenté, no debéis comparar el resultado con lo que uno espera que dé una función específica. De [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-4.md#sobre-la-programaci%C3%B3n):

> El error principal es testear que las funciones dan la salida esperada, es decir, aplicar la lógica de negocio y si uno espera que el resultado sea X, comprobar que es X. En realidad, no es así. Hay que comprobar que se cumple lo que pide la lógica de negocio. Si se pide que algo sea mínimo, o mejor, u óptimo, hay que comprobar que efectivamente el resultado es el mínimo, o mejor que otros, u óptimo; hay que tener una función que compruebe la "bondad" o lo que sea de la solución y mostrar que efectivamente es la mejor según ese criterio. Esto es repetir lo de arriba, pero hay que tenerlo en cuenta a la hora de escribir los tests. En tu HU #2 dices:

> Quiero una forma de optimizar mi tiempo para poder equilibrar mis estudios, el ejercicio físico y las citas médicas sin sentirme abrumada.

Lo que tienes, primero, es definir qué significa "equilibrado" (¿por día? ¿por semana? ¿bien repartido a lo largo de la semana?) y a continuación crear un test que efectivamente compruebe que tu solución optimiza el tiempo y está equilibrada.

2023-11-28 09:43 UTC, carlotiii30 commented on src/actividad.ts
> +        if (duracion === undefined) {
Utilizo tanto `hora` como `duracion` porque las actividades fijas tienen un horario fijo, comprendido entre un número de horas que no se pueden alterar. Sin embargo, las actividades variables no tienen una hora de comienzo o de fin, simplemente una cantidad de tiempo asignado a la semana, que es el que debe repartirse.

2023-11-28 10:08 UTC, carlotiii30 commented on src/actividad.ts
> +        if (duracion === undefined) {
Vale, ya entiendo, lo cambio. Muchas gracias.

2023-11-30 11:41 UTC, carlotiii30 commented
@JJ Listo para revisión

2023-11-30 12:04 UTC, JJ requested changes
Ha mejorado muchísimo, y te agradezco el trabajo realizado. El principal problema es que no se testea completamente la lógica de negocio, tal como está enunciada en la HU. El resto acumulativamente también son un obstáculo para superar el objetivo, así que te agradecería que les dieras una vuelta.

2023-11-30 12:04 UTC, JJ commented on src/optimizador_semanal.ts
> +            const horaInicioActividad = hora.split("-")[0];
Si no usas el tipo adecuado para almacenar las variables, esto es lo que sucede luego...

2023-11-30 12:04 UTC, JJ commented on test/optimizador_semanal.test.ts
> +                .flat() // Aplanar la matriz para facilitar la búsqueda
Si necesitas aplanarlo para poder trabajar con él, ¿por qué no lo almacenas así desde el principio?

2023-11-30 12:04 UTC, JJ commented on test/optimizador_semanal.test.ts
> +                .find(cell => cell === descripcion);
¿Seguro que #2 no necesita alguna comprobació más? ¿Las actividades fijas, están en el horario correcto? ¿Qué pasa si no puedes acomodar todas las actividades variables con las fijas?

2023-12-01 13:24 UTC, JJ approved these changes
Por favor, mira las cosas comentadas antes sobre tipos y arréglalas si puede ser antes del siguiente PR, te simplificará la vida.

2023-12-02 14:47 UTC, merged