[IV-23-24] Objetivo 1- Planificación del proyecto
carlotiii30/organizacionSemanal pull request #3
Opened 2023-09-26 10:59 UTC by carlotiii30

## Milestones

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

## Historias de usuario
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-26 15:01 UTC, LuciaAnsino commented on docs/milestones.md
> +[M0] Modelo del problema
Tienes que indicar en el M0 que es lo que entregas o proporcionas al hacerlo.

2023-09-26 15:29 UTC, LuciaAnsino commented on docs/historias_usuario.md
> +# Historias de usuario
Trata de indicar de dónde se obtiene la información con la que se trabajará, es decir, de dónde se obtiene la información que se debe de organizar.

2023-09-29 07:27 UTC, LuciaAnsino commented on docs/milestones.md
> +# Milestones
Deberías de poner otro milestone dónde se aborde la organización eficiente de los eventos del usuario, es decir, dónde se resuelva el problema principal

2023-09-29 07:37 UTC, LuciaAnsino approved these changes

2023-09-29 07:40 UTC, carlotiii30 commented
@JJ Listo para revisión

2023-09-29 08:24 UTC, JJ requested changes
Adicionalmente, ficheros como `.DS_Store` no deben añadirse al repo; ya os dije que no hiciérais lo de `git add .`, pero incluso aunque se haga accidentalmente, esos ficheros deben añadirse al `.gitignore`

2023-09-29 08:24 UTC, JJ commented on docs/milestones.md
> +[M1] Desarrollo de una función de creación de eventos.
Pueden ser una o 40. Lo esencial no es que se desarrolle una función, sino que se implemente la lógica de negocio

2023-09-29 08:24 UTC, JJ commented on docs/milestones.md
> +- Código fuente de la clase.
Esto no lo vamos a hacer, pero en todo caso la descripción del producto tendría que incluir qué tiene que hacer el sistema de notificaciones y qué lo hace viable.

2023-10-02 18:16 UTC, JJ approved these changes
:100: con gracias a @LuciaAnsino 
Antes de fusionar, sin embargo, convendría que especificaras un poco más los diferentes aspectos del problema: que hay citas que pueden ser movibles y las que no, que algunas necesitan una cantidad de horas en semana, por ejemplo. Si no, va a ser muy complicado para quien le toque trabajar en el objetivo 2 (o va a tomar decisiones en ese aspecto con las que igual no te sientes identificada)

2023-10-02 18:16 UTC, JJ commented on docs/historias_usuario.md
> +las personas, sobretodo, de mi persona. Quiero una forma de optimizar mi tiempo para
sobre todo está separado.
Si añades tu repo al hacktoberfest (poner tema "hacktoberfest" en la descripción del mismo) te puedo hacer un PR que compruebe ortográficamente y de formato cualquier fichero markdown.

2023-10-02 18:16 UTC, JJ commented on docs/historias_usuario.md
> +las citas médicas tendría que ir apuntándolas yo conforme vaya
Lo de las citas médicas me parece muy específico. Seguramente sería conveniente manejar todo tipo de citas.

2023-10-02 18:46 UTC, merged