[IV-23-24]Objetivo 6
carlotiii30/organizacionSemanal pull request #63
Opened 2023-12-11 14:45 UTC by carlotiii30

* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   dellenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-12-12 08:39 UTC, PabloBarTo approved these changes
En general lo veo todo bastante bien👌

2023-12-12 12:53 UTC, carlotiii30 commented
> En general lo veo todo bastante bien👌

Gracias!

@JJ Listo para revisión

2023-12-12 16:16 UTC, JJ requested changes
Bien por haber buscado distintos sistemas, especialmente gitlab; todavía podrías haber examinado alguno más, pero sobre todo el problema es cómo estás usando los contenedores. Por favor, repásalo.

2023-12-12 16:16 UTC, JJ commented on .github/workflows/ci.yml
> +        node-version: ['20', '21']
En actions/setup-node puedes ver una serie de nombres o versiones "semánticas", que no designan versión específica, sino la que en cada momento tiene ese rol. Consúltalo, por favor, y úsalos en vez de estas versiones.

2023-12-12 16:16 UTC, JJ commented on .travis.yml
> +  - docker run -v $(pwd):/app carlotiii30/organizacionsemanal yarn install
Me temo que si haces esto, cada uno se estará haciendo en un contenedor diferente. Además, de lo que se trata es de que llames directamente al entrypoint con docker run; en este caso no sé exactamente que estará haciendo, pero casi seguro que no es lo que tú quieres, porque tampoco lo estás montando en el `workdir`

2023-12-12 18:15 UTC, carlotiii30 commented on .travis.yml
> +  - docker run -v $(pwd):/app carlotiii30/organizacionsemanal yarn install
Resuelto en https://github.com/carlotiii30/organizacionSemanal/pull/63/commits/931f030acc778db45077a5d92d8e918c4c89ff3c

2023-12-12 18:15 UTC, carlotiii30 commented on .github/workflows/ci.yml
> +        node-version: ['20', '21']
Resuelto en https://github.com/carlotiii30/organizacionSemanal/pull/63/commits/b8431c2cfdd1488580993d12701f9d02584fab2a

2023-12-15 07:40 UTC, JJ requested changes
Gracias por corregirlo tan rápidamente; el principal problema es que no estoy seguro de que estés testeando todo el rango de versiones posibles. Puede ser cuestión de documentación (porque no sé la versión que se usa en el contenedor) o efectivamente de versiones que puedas usar donde las estés probando. Te agradecería en cualquier caso que lo aclararas.

2023-12-15 07:40 UTC, JJ commented on .gitlab-ci.yml
> +  image: carlotiii30/organizacionsemanal
¿Estás segura de que la versión que tienes en este contenedor es diferente de las otras dos que estás testeando?

2023-12-15 07:40 UTC, JJ commented on docs/ci.md
> +Como podemos ver en la [página oficial de Node.js](https://nodejs.org/en), la
Pero tienes 4 tests; 2 en GitHub y uno en cada uno de los otros, aunque en los otros tienes el mismo contenedor. Hay tres versiones "interesantes": las LTS antiguas, la LTS actual, o estable, o `current`, y la de desarrollo. ¿Te has asegurado de testearlas todas?

2023-12-15 08:12 UTC, carlotiii30 commented on docs/ci.md
> +Como podemos ver en la [página oficial de Node.js](https://nodejs.org/en), la
Resuelto en https://github.com/carlotiii30/organizacionSemanal/pull/63/commits/cbe54784a3435252a8fc46ab4f2456e1d7ac93ad

2023-12-15 08:15 UTC, carlotiii30 commented on .gitlab-ci.yml
> +  image: carlotiii30/organizacionsemanal
Aclarado en https://github.com/carlotiii30/organizacionSemanal/pull/63/commits/0a5a6634566de13b1edcfb2bec676c7619b19fe6

2023-12-15 08:37 UTC, JJ approved these changes
👍

2023-12-15 09:02 UTC, merged