[IV-23-24] Objetivo 8
carlotiii30/organizacionSemanal pull request #85
Opened 2023-12-25 11:03 UTC by carlotiii30

* [ ] ¿Has justificado tu elección de un framework REST y explicado por qué no has
   elegido ni `flask` ni `express`?
* [ ] ¿Las rutas están organizadas alrededor de un recurso?
* [ ] ¿Has usado cada verbo HTTP con su forma convencional más aceptada?

2023-12-28 11:03 UTC, danieeeld2 commented on src/controlador.ts
> +  comprobarEstado(): string {
Mi duda aquí es sobre por qué el `GET` no es sobre `recurso`, como el resto de endpoints de la API, porque, entiendo qué, al ser un organizador semanal/agenda, necesitarás hacer un `GET` de todas las actividades programadas o sobre un conjunto específico.

2023-12-28 17:41 UTC, carlotiii30 commented on docs/api_rest.md
> +- **Verbos HTTP**: Facilidad para la declaración de los verbos HTTP asociados
Entiendo que pueda generar confusión. Lo he cambiado para especificar mejor a lo que me refiero en el siguiente commit: https://github.com/carlotiii30/organizacionSemanal/pull/85/commits/03b3d8a43f98bac30314ec68068d75b6a2db1a10

2023-12-28 17:42 UTC, carlotiii30 commented on src/controlador.ts
> +  comprobarEstado(): string {
Tienes razón. Entendí en el guión que necesitábamos tener una "ruta de comprobación" y por eso use el GET, pero claro, debería estar definido también alrededor de un recurso, como bien dices. Ya lo he cambiado (https://github.com/carlotiii30/organizacionSemanal/pull/85/commits/03b3d8a43f98bac30314ec68068d75b6a2db1a10). Muchas gracias

2023-12-29 10:38 UTC, danieeeld2 approved these changes
:+1: Creo que ya está bien. La única duda que me queda es cómo se ve el path/endpoint en la API con la librería que estas usando,  por ejemplo, cuando haces `Get(:id)`, ¿se vería como `/recurso/{id}`?

2023-12-29 10:59 UTC, carlotiii30 commented
> 👍 Creo que ya está bien. La única duda que me queda es cómo se ve el path/endpoint en la API con la librería que estas usando, por ejemplo, cuando haces `Get(:id)`, ¿se vería como `/recurso/{id}`?

Más o menos, al definir el controller a "organizador" los endpoints serían `/organizador/{id}`

2023-12-29 11:08 UTC, carlotiii30 commented
@JJ Listo para revisión

2023-12-29 11:21 UTC, JJ requested changes
Muchas gracias a @danieeeld2 por la revisión. El principal problema que veo es que estás usando recursos genéricos, sin definirlos específicamente para tu problema Por lo que estoy viendo [aquí](https://docs.nestjs.com/controllers) se tiene que hacer una operación equivalente para cada objeto. En tu caso estás por tanto definiendo las rutas `/organizador`, trabajando por tanto con URIs tipo `organizador/{id]`, como dices [aquí](https://github.com/carlotiii30/organizacionSemanal/pull/85#issuecomment-1871951053), pero el problema es que tu recursos principal no es el organizador, sino las tareas, según yo entiendo. Las tareas podrán ser subrutas (sub-URIs) de `organizador`.
El hecho de que trabajes con `organizador` hace que sea un poco dudosa la necesidad de borrarlo (¿qué significa borrar un organizador?) o de usar a la vez `POST` y `PUT` (¿conoces la ID del organizador antes de crearlo? La diferencia entre PUT y POST es básicamente quién crea el ID específico de cada URI; además, para POST se suele usar el prural del sustantivo para indicar que es el que crea recurso*s* de ese tipo)

2023-12-29 11:21 UTC, JJ commented on package.json
> +    "rxjs": "^7.8.1"
¿Esto es una dependencia directa?

2023-12-29 11:21 UTC, JJ commented on src/controlador.ts
> +    LoggerConfig.logger.info('Recursos obtenidos');
Esto devolverá un objeto, ¿no has considerado la posibilidad de definirlo como una variable de instancia?

2023-12-29 12:00 UTC, carlotiii30 commented on package.json
> +    "rxjs": "^7.8.1"
Es, efectivamente, una dependencia indirecta, la necesita nestjs y he comprobado que se instala con `@nestjs/core`. Resuelto en https://github.com/carlotiii30/organizacionSemanal/pull/85/commits/0d6d80c7e7355c8b2ba0ca7888439b66b34451bb.

2023-12-29 12:01 UTC, carlotiii30 commented on src/controlador.ts
> +    LoggerConfig.logger.info('Recursos obtenidos');
Creo que se refiere a esto https://github.com/carlotiii30/organizacionSemanal/pull/85/commits/48e0a024229790f211ce25ab9eefacb41f20e7b5 ?

2023-12-29 12:04 UTC, carlotiii30 commented
> Muchas gracias a @danieeeld2 por la revisión. El principal problema que veo es que estás usando recursos genéricos, sin definirlos específicamente para tu problema Por lo que estoy viendo [aquí](https://docs.nestjs.com/controllers) se tiene que hacer una operación equivalente para cada objeto. En tu caso estás por tanto definiendo las rutas `/organizador`, trabajando por tanto con URIs tipo `organizador/{id]`, como dices [aquí](https://github.com/carlotiii30/organizacionSemanal/pull/85#issuecomment-1871951053), pero el problema es que tu recursos principal no es el organizador, sino las tareas, según yo entiendo. Las tareas podrán ser subrutas (sub-URIs) de `organizador`. El hecho de que trabajes con `organizador` hace que sea un poco dudosa la necesidad de borrarlo (¿qué significa borrar un organizador?) o de usar a la vez `POST` y `PUT` (¿conoces la ID del organizador antes de crearlo? La diferencia entre PUT y POST es básicamente quién crea el ID específico de cada URI; además, para POST se suele usar el prural del sustantivo para indicar que es el que crea recurso_s_ de ese tipo)

He tenido en cuenta su comentario, es mucho más simple que el endpoint sea `/tareas`, ya que es lo que estamos manejando. Lo he resuelto.

2023-12-29 12:08 UTC, JJ commented on src/controlador.ts
> +    LoggerConfig.logger.info('Recursos obtenidos');
No, me refería al logger, perdón por no hacerlo lo suficientemente claro. `LoggerConfig.logger` es un objeto, y será siempre el mismo, ¿no?

2023-12-29 12:10 UTC, JJ approved these changes
:+1: 
Ahora a por el último :1st_place_medal:

2023-12-29 12:18 UTC, carlotiii30 commented on src/logger.ts
> +import * as fs from 'fs';
Al instalar las dependencias de nestjs, por alguna razón, no era capaz de resolver ese import. Al cambiarlo sí que lo hacia bien.

2023-12-29 12:20 UTC, carlotiii30 commented on tsconfig.json
> +    "experimentalDecorators": true,                   /* Enable experimental support for legacy experimental decorators. */
Resuelto en https://github.com/carlotiii30/organizacionSemanal/pull/85/commits/37df84bc14d70f2eb074e054ec97653960505054

2023-12-29 14:05 UTC, merged